repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: local
    hooks:
      - id: black
        name: Formatting (black)
        entry: poetry run black .
        language: system
        types: [ python ]
        stages: [ commit ]
      - id: isort
        name: Ordering imports (isort)
        entry: poetry run isort .
        language: system
        types: [ python ]
        stages: [ commit ]
#      - id: lint
#        name: Linter (pylint)
#        entry: poetry run pylint .
#        language: system
#        types: [ python ]
#        stages: [ commit ]
      - id: test
        name: Unit tests (pytest)
        entry: make test
        language: system
        types: [ python ]
        stages: [ push ]
